CREATE TABLE [ORDER_ITEM] (
  [OrderNumber] LONG  CONSTRAINT [RETAIL_ORDERORDER_ITEM] REFERENCES [RETAIL_ORDER] ([OrderNumber]),
  [SKU] LONG  CONSTRAINT [{3F618312-8959-4DD7-970D-23F4B02E82D5}] REFERENCES [SKU_DATA] ([SKU]),
  [Quantity] SHORT ,
  [Price] CURRENCY ,
  [ExtendedPrice] CURRENCY ,
   CONSTRAINT [ORDER_ITEM_PK] PRIMARY KEY ([SKU], [OrderNumber])
)
